name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      # https://github.com/marketplace/actions/release-me
      - name: Release
        uses: ridedott/release-me-action@master
        with:
          node-module: true
        env:
          GITHUB_TOKEN: ${{ secrets.PROTECTED_BRANCH_GITHUB_ACCESS_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@mileszim'

      - run: yarn install
      - run: yarn run build

      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
